#sleepyhollow wezterm
[colors]
foreground="#eef1f8"
background="#07080d"
cursor_fg="#07080d"
cursor_bg="#eef1f8"

ansi=[
    "#14161b",
    "#9a7ee6",
    "#8be896",
    "#f0cc7a",
    "#68bdf2",
    "#f294f2",
    "#52ebeb",
    "#E0E2EA",
]

brights=[
    "#2c2e33",
    "#beb3f2",
    "#b4f6c0",
    "#fce095",
    "#a6dbff",
    "#ffcaff",
    "#8cf8f7",
    "#eef1f8",
]
