#colorscheme based on gentoo colors
# https://wiki.gentoo.org/wiki/Project:Artwork/Colors
[colors]
foreground="#dddaec"
background="#000000"
cursor_fg="#000000"
cursor_bg="#dddaec"

ansi=[
    "#282a2e",
    "#af475a",
    "#6b59a4",
    "#40947a",
    "#4150b1",
    "#975dbf",
    "#3787ae",
    "#7b7680",
]

brights=[
    "#373b41",
    "#c88a96",
    "#9f8ddb",
    "#7eb9a7",
    "#798be1",
    "#b887da",
    "#76bede",
    "#e1e1e1",
]
