#colorscheme based on gentoo colors
# https://wiki.gentoo.org/wiki/Project:Artwork/Colors
[colors]
foreground="#dddaec"
background="#000000"
cursor_fg="#000000"
cursor_bg="#dddaec"

ansi=[
    "#282a2e",
    "#c05b75",
    "#77c686",
    "#7a65bb",
    "#78a9db",
    "#d480e3",
    "#58b3ca",
    "#7b7680",
]

brights=[
    "#373b41",
    "#c88a96",
    "#b4f6c0",
    "#b8a2ff",
    "#a6d2ff",
    "#e4a5ef",
    "#88e7ff",
    "#e1e1e1",
]
