#greenandred wezterm theme by david
[colors]
foreground="#fadccf"
background="#0b0b0c"
cursor_fg="#0b0b0c"
cursor_bg="#fadccf"

ansi=[
    "#3d3b4b",
    "#da3c3c",
    "#3ebf62",
    "#cc6946",
    "#3ea782",
    "#ec4671",
    "#33bc77",
    "#fdded1",
]

brights=[
    "#4e4b61",
    "#e95a5a",
    "#6ef28c",
    "#ff9972",
    "#69e4be",
    "#fa90a7",
    "#67f2a6",
    "#f7e9c7",
]
