#lostwoods wezterm theme
[colors]
foreground="#fcfcfc"
background="#04171d"
cursor_bg="#04171d"
cursor_fg="#fcfcfc"

ansi=[
    "#202d30",
    "#d13434",
    "#00715d",
    "#006f32",
    "#a43261",
    "#913e88",
    "#007086",
    "#e7e4e4",
    ]

brights=[
    "#3f595e",
    "#c85e5e",
    "#24dfc4",
    "#73db95",
    "#ff9fc9",
    "#ffa7f6",
    "#00ddf4",
    "#fef5f5",
]

