#greenandred wezterm theme by david
[colors]
foreground="#fadccf"
background="#0b0b0c"
cursor_fg="#0b0b0c"
cursor_bg="#fadccf"

ansi=[
    "#3d3b4b",
    "#ec2243",
    "#e43779",
    "#ff8677",
    "#3774ad",
    "#6e56af",
    "#4fc4e1",
    "#fdded1",
]

brights=[
    "#4e4b61",
    "#d43e51",
    "#f473a4",
    "#ffa59a",
    "#6195c6",
    "#927ad3",
    "#86dce8",
    "#f7e9c7",
]
