#sea-anemone wezterm theme by david
[colors]
foreground="#fadccf"
background="#0b0b0c"
cursor_bg="#0b0b0c"
cursor_fg="#fadccf"

ansi=[
    "#3d3b4b",
    "#ba3934",
    "#bd9530",
    "#b55600",
    "#5f63b4",
    "#ea7eae",
    "#91b3af",
    "#fdded1",
]
brights=[
    "#4e4b61",
    "#d9443f",
    "#d6b04e",
    "#f66813",
    "#8086ef",
    "#f1b3d9",
    "#99d9e7",
    "#f7e9c7",
]
